
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.oracle.xmlns.primavera.p6.ws.job.v1;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-07-31T15:56:20.186+05:30
 * Generated source version: 3.1.11
 * 
 */

@javax.jws.WebService(
                      serviceName = "JobServiceV1",
                      portName = "JobPort",
                      targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Job/V1",
                      wsdlLocation = "https://nyuhospitals-dev-p6.oracleindustry.com/p6ws/services/V1/JobService?wsdl",
                      endpointInterface = "com.oracle.xmlns.primavera.p6.ws.job.v1.JobPortType")
                      
public class JobPortImpl implements JobPortType {

    private static final Logger LOG = Logger.getLogger(JobPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.oracle.xmlns.primavera.p6.ws.job.v1.JobPortType#schedule(int projectObjectId, javax.xml.datatype.XMLGregorianCalendar newDataDate, java.lang.Integer timeout, java.lang.String jobId, com.oracle.xmlns.primavera.p6.ws.job.v1.JobStatusType jobStatus)*
     */
    public void schedule(int projectObjectId, javax.xml.datatype.XMLGregorianCalendar newDataDate, java.lang.Integer timeout, javax.xml.ws.Holder<java.lang.String> jobId, javax.xml.ws.Holder<JobStatusType> jobStatus) throws IntegrationFault   { 
        LOG.info("Executing operation schedule");
        System.out.println(projectObjectId);
        System.out.println(newDataDate);
        System.out.println(timeout);
        try {
            java.lang.String jobIdValue = "";
            jobId.value = jobIdValue;
            com.oracle.xmlns.primavera.p6.ws.job.v1.JobStatusType jobStatusValue = null;
            jobStatus.value = jobStatusValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IntegrationFault("IntegrationFault...");
    }

    /* (non-Javadoc)
     * @see com.oracle.xmlns.primavera.p6.ws.job.v1.JobPortType#getCurrentJobs(java.lang.Object params)*
     */
    public com.oracle.xmlns.primavera.p6.ws.job.v1.GetCurrentJobsResponse getCurrentJobs(java.lang.Object params) throws IntegrationFault   { 
        LOG.info("Executing operation getCurrentJobs");
        System.out.println(params);
        try {
            com.oracle.xmlns.primavera.p6.ws.job.v1.GetCurrentJobsResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IntegrationFault("IntegrationFault...");
    }

    /* (non-Javadoc)
     * @see com.oracle.xmlns.primavera.p6.ws.job.v1.JobPortType#summarizeProject(int objectId, java.lang.Integer timeout, java.lang.String jobId, com.oracle.xmlns.primavera.p6.ws.job.v1.JobStatusType jobStatus)*
     */
    public void summarizeProject(int objectId, java.lang.Integer timeout, javax.xml.ws.Holder<java.lang.String> jobId, javax.xml.ws.Holder<JobStatusType> jobStatus) throws IntegrationFault   { 
        LOG.info("Executing operation summarizeProject");
        System.out.println(objectId);
        System.out.println(timeout);
        try {
            java.lang.String jobIdValue = "";
            jobId.value = jobIdValue;
            com.oracle.xmlns.primavera.p6.ws.job.v1.JobStatusType jobStatusValue = null;
            jobStatus.value = jobStatusValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IntegrationFault("IntegrationFault...");
    }

    /* (non-Javadoc)
     * @see com.oracle.xmlns.primavera.p6.ws.job.v1.JobPortType#summarizeEPS(int objectId, java.lang.Integer timeout, java.lang.String jobId, com.oracle.xmlns.primavera.p6.ws.job.v1.JobStatusType jobStatus)*
     */
    public void summarizeEPS(int objectId, java.lang.Integer timeout, javax.xml.ws.Holder<java.lang.String> jobId, javax.xml.ws.Holder<JobStatusType> jobStatus) throws IntegrationFault   { 
        LOG.info("Executing operation summarizeEPS");
        System.out.println(objectId);
        System.out.println(timeout);
        try {
            java.lang.String jobIdValue = "";
            jobId.value = jobIdValue;
            com.oracle.xmlns.primavera.p6.ws.job.v1.JobStatusType jobStatusValue = null;
            jobStatus.value = jobStatusValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IntegrationFault("IntegrationFault...");
    }

    /* (non-Javadoc)
     * @see com.oracle.xmlns.primavera.p6.ws.job.v1.JobPortType#applyActuals(int projectObjectId, javax.xml.datatype.XMLGregorianCalendar newDataDate, java.lang.Integer timeout, java.lang.String jobId, com.oracle.xmlns.primavera.p6.ws.job.v1.JobStatusType jobStatus)*
     */
    public void applyActuals(int projectObjectId, javax.xml.datatype.XMLGregorianCalendar newDataDate, java.lang.Integer timeout, javax.xml.ws.Holder<java.lang.String> jobId, javax.xml.ws.Holder<JobStatusType> jobStatus) throws IntegrationFault   { 
        LOG.info("Executing operation applyActuals");
        System.out.println(projectObjectId);
        System.out.println(newDataDate);
        System.out.println(timeout);
        try {
            java.lang.String jobIdValue = "";
            jobId.value = jobIdValue;
            com.oracle.xmlns.primavera.p6.ws.job.v1.JobStatusType jobStatusValue = null;
            jobStatus.value = jobStatusValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IntegrationFault("IntegrationFault...");
    }

    /* (non-Javadoc)
     * @see com.oracle.xmlns.primavera.p6.ws.job.v1.JobPortType#recalculateAssignmentCosts(int projectObjectId, boolean synchronizeOvertimeFactor, java.lang.Integer timeout, java.lang.String jobId, com.oracle.xmlns.primavera.p6.ws.job.v1.JobStatusType jobStatus)*
     */
    public void recalculateAssignmentCosts(int projectObjectId, boolean synchronizeOvertimeFactor, java.lang.Integer timeout, javax.xml.ws.Holder<java.lang.String> jobId, javax.xml.ws.Holder<JobStatusType> jobStatus) throws IntegrationFault   { 
        LOG.info("Executing operation recalculateAssignmentCosts");
        System.out.println(projectObjectId);
        System.out.println(synchronizeOvertimeFactor);
        System.out.println(timeout);
        try {
            java.lang.String jobIdValue = "";
            jobId.value = jobIdValue;
            com.oracle.xmlns.primavera.p6.ws.job.v1.JobStatusType jobStatusValue = null;
            jobStatus.value = jobStatusValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IntegrationFault("IntegrationFault...");
    }

    /* (non-Javadoc)
     * @see com.oracle.xmlns.primavera.p6.ws.job.v1.JobPortType#readJobStatus(java.lang.String jobId)*
     */
    public com.oracle.xmlns.primavera.p6.ws.job.v1.JobStatusType readJobStatus(java.lang.String jobId) throws IntegrationFault   { 
        LOG.info("Executing operation readJobStatus");
        System.out.println(jobId);
        try {
            com.oracle.xmlns.primavera.p6.ws.job.v1.JobStatusType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IntegrationFault("IntegrationFault...");
    }

    /* (non-Javadoc)
     * @see com.oracle.xmlns.primavera.p6.ws.job.v1.JobPortType#level(int projectObjectId, java.lang.Integer timeout, java.lang.String jobId, com.oracle.xmlns.primavera.p6.ws.job.v1.JobStatusType jobStatus)*
     */
    public void level(int projectObjectId, java.lang.Integer timeout, javax.xml.ws.Holder<java.lang.String> jobId, javax.xml.ws.Holder<JobStatusType> jobStatus) throws IntegrationFault   { 
        LOG.info("Executing operation level");
        System.out.println(projectObjectId);
        System.out.println(timeout);
        try {
            java.lang.String jobIdValue = "";
            jobId.value = jobIdValue;
            com.oracle.xmlns.primavera.p6.ws.job.v1.JobStatusType jobStatusValue = null;
            jobStatus.value = jobStatusValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IntegrationFault("IntegrationFault...");
    }

    /* (non-Javadoc)
     * @see com.oracle.xmlns.primavera.p6.ws.job.v1.JobPortType#storePeriodPerformance(java.util.List<java.lang.Integer> projectObjectId, int financialPeriodObjectId, java.lang.Integer timeout, java.lang.String jobId, com.oracle.xmlns.primavera.p6.ws.job.v1.JobStatusType jobStatus)*
     */
    public void storePeriodPerformance(java.util.List<java.lang.Integer> projectObjectId, int financialPeriodObjectId, java.lang.Integer timeout, javax.xml.ws.Holder<java.lang.String> jobId, javax.xml.ws.Holder<JobStatusType> jobStatus) throws IntegrationFault   { 
        LOG.info("Executing operation storePeriodPerformance");
        System.out.println(projectObjectId);
        System.out.println(financialPeriodObjectId);
        System.out.println(timeout);
        try {
            java.lang.String jobIdValue = "";
            jobId.value = jobIdValue;
            com.oracle.xmlns.primavera.p6.ws.job.v1.JobStatusType jobStatusValue = null;
            jobStatus.value = jobStatusValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IntegrationFault("IntegrationFault...");
    }

    /* (non-Javadoc)
     * @see com.oracle.xmlns.primavera.p6.ws.job.v1.JobPortType#cancelJob(java.lang.String jobId)*
     */
    public com.oracle.xmlns.primavera.p6.ws.job.v1.JobStatusType cancelJob(java.lang.String jobId) throws IntegrationFault   { 
        LOG.info("Executing operation cancelJob");
        System.out.println(jobId);
        try {
            com.oracle.xmlns.primavera.p6.ws.job.v1.JobStatusType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IntegrationFault("IntegrationFault...");
    }

}
