
package com.oracle.xmlns.primavera.p6.ws.job.v1;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-07-31T15:56:19.887+05:30
 * Generated source version: 3.1.11
 * 
 */
public final class JobPortType_JobPort_Client {

    private static final QName SERVICE_NAME = new QName("http://xmlns.oracle.com/Primavera/P6/WS/Job/V1", "JobServiceV1");

    private JobPortType_JobPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = JobServiceV1.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        JobServiceV1 ss = new JobServiceV1(wsdlURL, SERVICE_NAME);
        JobPortType port = ss.getJobPort();  
        
        {
        System.out.println("Invoking schedule...");
        int _schedule_projectObjectId = 0;
        javax.xml.datatype.XMLGregorianCalendar _schedule_newDataDate = null;
        java.lang.Integer _schedule_timeout = null;
        javax.xml.ws.Holder<java.lang.String> _schedule_jobId = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<com.oracle.xmlns.primavera.p6.ws.job.v1.JobStatusType> _schedule_jobStatus = new javax.xml.ws.Holder<com.oracle.xmlns.primavera.p6.ws.job.v1.JobStatusType>();
        try {
            port.schedule(_schedule_projectObjectId, _schedule_newDataDate, _schedule_timeout, _schedule_jobId, _schedule_jobStatus);

            System.out.println("schedule._schedule_jobId=" + _schedule_jobId.value);
            System.out.println("schedule._schedule_jobStatus=" + _schedule_jobStatus.value);
        } catch (IntegrationFault e) { 
            System.out.println("Expected exception: IntegrationFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getCurrentJobs...");
        java.lang.Object _getCurrentJobs_params = new java.lang.Object();
        try {
            com.oracle.xmlns.primavera.p6.ws.job.v1.GetCurrentJobsResponse _getCurrentJobs__return = port.getCurrentJobs(_getCurrentJobs_params);
            System.out.println("getCurrentJobs.result=" + _getCurrentJobs__return);

        } catch (IntegrationFault e) { 
            System.out.println("Expected exception: IntegrationFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking summarizeProject...");
        int _summarizeProject_objectId = 0;
        java.lang.Integer _summarizeProject_timeout = null;
        javax.xml.ws.Holder<java.lang.String> _summarizeProject_jobId = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<com.oracle.xmlns.primavera.p6.ws.job.v1.JobStatusType> _summarizeProject_jobStatus = new javax.xml.ws.Holder<com.oracle.xmlns.primavera.p6.ws.job.v1.JobStatusType>();
        try {
            port.summarizeProject(_summarizeProject_objectId, _summarizeProject_timeout, _summarizeProject_jobId, _summarizeProject_jobStatus);

            System.out.println("summarizeProject._summarizeProject_jobId=" + _summarizeProject_jobId.value);
            System.out.println("summarizeProject._summarizeProject_jobStatus=" + _summarizeProject_jobStatus.value);
        } catch (IntegrationFault e) { 
            System.out.println("Expected exception: IntegrationFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking summarizeEPS...");
        int _summarizeEPS_objectId = 0;
        java.lang.Integer _summarizeEPS_timeout = null;
        javax.xml.ws.Holder<java.lang.String> _summarizeEPS_jobId = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<com.oracle.xmlns.primavera.p6.ws.job.v1.JobStatusType> _summarizeEPS_jobStatus = new javax.xml.ws.Holder<com.oracle.xmlns.primavera.p6.ws.job.v1.JobStatusType>();
        try {
            port.summarizeEPS(_summarizeEPS_objectId, _summarizeEPS_timeout, _summarizeEPS_jobId, _summarizeEPS_jobStatus);

            System.out.println("summarizeEPS._summarizeEPS_jobId=" + _summarizeEPS_jobId.value);
            System.out.println("summarizeEPS._summarizeEPS_jobStatus=" + _summarizeEPS_jobStatus.value);
        } catch (IntegrationFault e) { 
            System.out.println("Expected exception: IntegrationFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking applyActuals...");
        int _applyActuals_projectObjectId = 0;
        javax.xml.datatype.XMLGregorianCalendar _applyActuals_newDataDate = null;
        java.lang.Integer _applyActuals_timeout = null;
        javax.xml.ws.Holder<java.lang.String> _applyActuals_jobId = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<com.oracle.xmlns.primavera.p6.ws.job.v1.JobStatusType> _applyActuals_jobStatus = new javax.xml.ws.Holder<com.oracle.xmlns.primavera.p6.ws.job.v1.JobStatusType>();
        try {
            port.applyActuals(_applyActuals_projectObjectId, _applyActuals_newDataDate, _applyActuals_timeout, _applyActuals_jobId, _applyActuals_jobStatus);

            System.out.println("applyActuals._applyActuals_jobId=" + _applyActuals_jobId.value);
            System.out.println("applyActuals._applyActuals_jobStatus=" + _applyActuals_jobStatus.value);
        } catch (IntegrationFault e) { 
            System.out.println("Expected exception: IntegrationFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking recalculateAssignmentCosts...");
        int _recalculateAssignmentCosts_projectObjectId = 0;
        boolean _recalculateAssignmentCosts_synchronizeOvertimeFactor = false;
        java.lang.Integer _recalculateAssignmentCosts_timeout = null;
        javax.xml.ws.Holder<java.lang.String> _recalculateAssignmentCosts_jobId = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<com.oracle.xmlns.primavera.p6.ws.job.v1.JobStatusType> _recalculateAssignmentCosts_jobStatus = new javax.xml.ws.Holder<com.oracle.xmlns.primavera.p6.ws.job.v1.JobStatusType>();
        try {
            port.recalculateAssignmentCosts(_recalculateAssignmentCosts_projectObjectId, _recalculateAssignmentCosts_synchronizeOvertimeFactor, _recalculateAssignmentCosts_timeout, _recalculateAssignmentCosts_jobId, _recalculateAssignmentCosts_jobStatus);

            System.out.println("recalculateAssignmentCosts._recalculateAssignmentCosts_jobId=" + _recalculateAssignmentCosts_jobId.value);
            System.out.println("recalculateAssignmentCosts._recalculateAssignmentCosts_jobStatus=" + _recalculateAssignmentCosts_jobStatus.value);
        } catch (IntegrationFault e) { 
            System.out.println("Expected exception: IntegrationFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking readJobStatus...");
        java.lang.String _readJobStatus_jobId = "";
        try {
            com.oracle.xmlns.primavera.p6.ws.job.v1.JobStatusType _readJobStatus__return = port.readJobStatus(_readJobStatus_jobId);
            System.out.println("readJobStatus.result=" + _readJobStatus__return);

        } catch (IntegrationFault e) { 
            System.out.println("Expected exception: IntegrationFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking level...");
        int _level_projectObjectId = 0;
        java.lang.Integer _level_timeout = null;
        javax.xml.ws.Holder<java.lang.String> _level_jobId = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<com.oracle.xmlns.primavera.p6.ws.job.v1.JobStatusType> _level_jobStatus = new javax.xml.ws.Holder<com.oracle.xmlns.primavera.p6.ws.job.v1.JobStatusType>();
        try {
            port.level(_level_projectObjectId, _level_timeout, _level_jobId, _level_jobStatus);

            System.out.println("level._level_jobId=" + _level_jobId.value);
            System.out.println("level._level_jobStatus=" + _level_jobStatus.value);
        } catch (IntegrationFault e) { 
            System.out.println("Expected exception: IntegrationFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking storePeriodPerformance...");
        java.util.List<java.lang.Integer> _storePeriodPerformance_projectObjectId = null;
        int _storePeriodPerformance_financialPeriodObjectId = 0;
        java.lang.Integer _storePeriodPerformance_timeout = null;
        javax.xml.ws.Holder<java.lang.String> _storePeriodPerformance_jobId = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<com.oracle.xmlns.primavera.p6.ws.job.v1.JobStatusType> _storePeriodPerformance_jobStatus = new javax.xml.ws.Holder<com.oracle.xmlns.primavera.p6.ws.job.v1.JobStatusType>();
        try {
            port.storePeriodPerformance(_storePeriodPerformance_projectObjectId, _storePeriodPerformance_financialPeriodObjectId, _storePeriodPerformance_timeout, _storePeriodPerformance_jobId, _storePeriodPerformance_jobStatus);

            System.out.println("storePeriodPerformance._storePeriodPerformance_jobId=" + _storePeriodPerformance_jobId.value);
            System.out.println("storePeriodPerformance._storePeriodPerformance_jobStatus=" + _storePeriodPerformance_jobStatus.value);
        } catch (IntegrationFault e) { 
            System.out.println("Expected exception: IntegrationFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking cancelJob...");
        java.lang.String _cancelJob_jobId = "";
        try {
            com.oracle.xmlns.primavera.p6.ws.job.v1.JobStatusType _cancelJob__return = port.cancelJob(_cancelJob_jobId);
            System.out.println("cancelJob.result=" + _cancelJob__return);

        } catch (IntegrationFault e) { 
            System.out.println("Expected exception: IntegrationFault has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
