package com.oracle.xmlns.primavera.p6.ws.job.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-07-31T15:56:20.224+05:30
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Job/V1", name = "JobPortType")
@XmlSeeAlso({ObjectFactory.class, com.oracle.xmlns.primavera.p6.ws.integrationfaulttype.v1.ObjectFactory.class})
public interface JobPortType {

    @WebMethod(operationName = "Schedule", action = "Schedule")
    @RequestWrapper(localName = "Schedule", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Job/V1", className = "com.oracle.xmlns.primavera.p6.ws.job.v1.Schedule")
    @ResponseWrapper(localName = "ScheduleResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Job/V1", className = "com.oracle.xmlns.primavera.p6.ws.job.v1.ScheduleResponse")
    public void schedule(
        @WebParam(name = "ProjectObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Job/V1")
        int projectObjectId,
        @WebParam(name = "NewDataDate", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Job/V1")
        javax.xml.datatype.XMLGregorianCalendar newDataDate,
        @WebParam(name = "Timeout", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Job/V1")
        java.lang.Integer timeout,
        @WebParam(mode = WebParam.Mode.OUT, name = "JobId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Job/V1")
        javax.xml.ws.Holder<java.lang.String> jobId,
        @WebParam(mode = WebParam.Mode.OUT, name = "JobStatus", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Job/V1")
        javax.xml.ws.Holder<JobStatusType> jobStatus
    ) throws IntegrationFault;

    @WebMethod(operationName = "GetCurrentJobs", action = "GetCurrentJobs")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "GetCurrentJobsResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Job/V1", partName = "result")
    public GetCurrentJobsResponse getCurrentJobs(
        @WebParam(partName = "params", name = "GetCurrentJobs", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Job/V1")
        java.lang.Object params
    ) throws IntegrationFault;

    @WebMethod(operationName = "SummarizeProject", action = "SummarizeProject")
    @RequestWrapper(localName = "SummarizeProject", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Job/V1", className = "com.oracle.xmlns.primavera.p6.ws.job.v1.SummarizeProject")
    @ResponseWrapper(localName = "SummarizeProjectResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Job/V1", className = "com.oracle.xmlns.primavera.p6.ws.job.v1.SummarizeProjectResponse")
    public void summarizeProject(
        @WebParam(name = "ObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Job/V1")
        int objectId,
        @WebParam(name = "Timeout", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Job/V1")
        java.lang.Integer timeout,
        @WebParam(mode = WebParam.Mode.OUT, name = "JobId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Job/V1")
        javax.xml.ws.Holder<java.lang.String> jobId,
        @WebParam(mode = WebParam.Mode.OUT, name = "JobStatus", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Job/V1")
        javax.xml.ws.Holder<JobStatusType> jobStatus
    ) throws IntegrationFault;

    @WebMethod(operationName = "SummarizeEPS", action = "SummarizeEPS")
    @RequestWrapper(localName = "SummarizeEPS", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Job/V1", className = "com.oracle.xmlns.primavera.p6.ws.job.v1.SummarizeEPS")
    @ResponseWrapper(localName = "SummarizeEPSResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Job/V1", className = "com.oracle.xmlns.primavera.p6.ws.job.v1.SummarizeEPSResponse")
    public void summarizeEPS(
        @WebParam(name = "ObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Job/V1")
        int objectId,
        @WebParam(name = "Timeout", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Job/V1")
        java.lang.Integer timeout,
        @WebParam(mode = WebParam.Mode.OUT, name = "JobId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Job/V1")
        javax.xml.ws.Holder<java.lang.String> jobId,
        @WebParam(mode = WebParam.Mode.OUT, name = "JobStatus", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Job/V1")
        javax.xml.ws.Holder<JobStatusType> jobStatus
    ) throws IntegrationFault;

    @WebMethod(operationName = "ApplyActuals", action = "ApplyActuals")
    @RequestWrapper(localName = "ApplyActuals", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Job/V1", className = "com.oracle.xmlns.primavera.p6.ws.job.v1.ApplyActuals")
    @ResponseWrapper(localName = "ApplyActualsResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Job/V1", className = "com.oracle.xmlns.primavera.p6.ws.job.v1.ApplyActualsResponse")
    public void applyActuals(
        @WebParam(name = "ProjectObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Job/V1")
        int projectObjectId,
        @WebParam(name = "NewDataDate", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Job/V1")
        javax.xml.datatype.XMLGregorianCalendar newDataDate,
        @WebParam(name = "Timeout", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Job/V1")
        java.lang.Integer timeout,
        @WebParam(mode = WebParam.Mode.OUT, name = "JobId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Job/V1")
        javax.xml.ws.Holder<java.lang.String> jobId,
        @WebParam(mode = WebParam.Mode.OUT, name = "JobStatus", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Job/V1")
        javax.xml.ws.Holder<JobStatusType> jobStatus
    ) throws IntegrationFault;

    @WebMethod(operationName = "RecalculateAssignmentCosts", action = "RecalculateAssignmentCosts")
    @RequestWrapper(localName = "RecalculateAssignmentCosts", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Job/V1", className = "com.oracle.xmlns.primavera.p6.ws.job.v1.RecalculateAssignmentCosts")
    @ResponseWrapper(localName = "RecalculateAssignmentCostsResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Job/V1", className = "com.oracle.xmlns.primavera.p6.ws.job.v1.RecalculateAssignmentCostsResponse")
    public void recalculateAssignmentCosts(
        @WebParam(name = "ProjectObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Job/V1")
        int projectObjectId,
        @WebParam(name = "SynchronizeOvertimeFactor", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Job/V1")
        boolean synchronizeOvertimeFactor,
        @WebParam(name = "Timeout", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Job/V1")
        java.lang.Integer timeout,
        @WebParam(mode = WebParam.Mode.OUT, name = "JobId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Job/V1")
        javax.xml.ws.Holder<java.lang.String> jobId,
        @WebParam(mode = WebParam.Mode.OUT, name = "JobStatus", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Job/V1")
        javax.xml.ws.Holder<JobStatusType> jobStatus
    ) throws IntegrationFault;

    @WebMethod(operationName = "ReadJobStatus", action = "ReadJobStatus")
    @RequestWrapper(localName = "ReadJobStatus", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Job/V1", className = "com.oracle.xmlns.primavera.p6.ws.job.v1.ReadJobStatus")
    @ResponseWrapper(localName = "ReadJobStatusResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Job/V1", className = "com.oracle.xmlns.primavera.p6.ws.job.v1.ReadJobStatusResponse")
    @WebResult(name = "JobStatus", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Job/V1")
    public com.oracle.xmlns.primavera.p6.ws.job.v1.JobStatusType readJobStatus(
        @WebParam(name = "JobId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Job/V1")
        java.lang.String jobId
    ) throws IntegrationFault;

    @WebMethod(operationName = "Level", action = "Level")
    @RequestWrapper(localName = "Level", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Job/V1", className = "com.oracle.xmlns.primavera.p6.ws.job.v1.Level")
    @ResponseWrapper(localName = "LevelResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Job/V1", className = "com.oracle.xmlns.primavera.p6.ws.job.v1.LevelResponse")
    public void level(
        @WebParam(name = "ProjectObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Job/V1")
        int projectObjectId,
        @WebParam(name = "Timeout", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Job/V1")
        java.lang.Integer timeout,
        @WebParam(mode = WebParam.Mode.OUT, name = "JobId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Job/V1")
        javax.xml.ws.Holder<java.lang.String> jobId,
        @WebParam(mode = WebParam.Mode.OUT, name = "JobStatus", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Job/V1")
        javax.xml.ws.Holder<JobStatusType> jobStatus
    ) throws IntegrationFault;

    @WebMethod(operationName = "StorePeriodPerformance", action = "StorePeriodPerformance")
    @RequestWrapper(localName = "StorePeriodPerformance", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Job/V1", className = "com.oracle.xmlns.primavera.p6.ws.job.v1.StorePeriodPerformance")
    @ResponseWrapper(localName = "StorePeriodPerformanceResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Job/V1", className = "com.oracle.xmlns.primavera.p6.ws.job.v1.StorePeriodPerformanceResponse")
    public void storePeriodPerformance(
        @WebParam(name = "ProjectObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Job/V1")
        java.util.List<java.lang.Integer> projectObjectId,
        @WebParam(name = "FinancialPeriodObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Job/V1")
        int financialPeriodObjectId,
        @WebParam(name = "Timeout", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Job/V1")
        java.lang.Integer timeout,
        @WebParam(mode = WebParam.Mode.OUT, name = "JobId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Job/V1")
        javax.xml.ws.Holder<java.lang.String> jobId,
        @WebParam(mode = WebParam.Mode.OUT, name = "JobStatus", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Job/V1")
        javax.xml.ws.Holder<JobStatusType> jobStatus
    ) throws IntegrationFault;

    @WebMethod(operationName = "CancelJob", action = "CancelJob")
    @RequestWrapper(localName = "CancelJob", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Job/V1", className = "com.oracle.xmlns.primavera.p6.ws.job.v1.CancelJob")
    @ResponseWrapper(localName = "CancelJobResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Job/V1", className = "com.oracle.xmlns.primavera.p6.ws.job.v1.CancelJobResponse")
    @WebResult(name = "JobStatus", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Job/V1")
    public com.oracle.xmlns.primavera.p6.ws.job.v1.JobStatusType cancelJob(
        @WebParam(name = "JobId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Job/V1")
        java.lang.String jobId
    ) throws IntegrationFault;
}
