package com.oracle.xmlns.primavera.p6.ws.job.v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-07-31T15:56:20.244+05:30
 * Generated source version: 3.1.11
 * 
 */
@WebServiceClient(name = "JobServiceV1", 
                  wsdlLocation = "https://nyuhospitals-dev-p6.oracleindustry.com/p6ws/services/V1/JobService?wsdl",
                  targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Job/V1") 
public class JobServiceV1 extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://xmlns.oracle.com/Primavera/P6/WS/Job/V1", "JobServiceV1");
    public final static QName JobPort = new QName("http://xmlns.oracle.com/Primavera/P6/WS/Job/V1", "JobPort");
    static {
        URL url = null;
        try {
            url = new URL("https://nyuhospitals-dev-p6.oracleindustry.com/p6ws/services/V1/JobService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(JobServiceV1.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "https://nyuhospitals-dev-p6.oracleindustry.com/p6ws/services/V1/JobService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public JobServiceV1(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public JobServiceV1(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JobServiceV1() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public JobServiceV1(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public JobServiceV1(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public JobServiceV1(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns JobPortType
     */
    @WebEndpoint(name = "JobPort")
    public JobPortType getJobPort() {
        return super.getPort(JobPort, JobPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns JobPortType
     */
    @WebEndpoint(name = "JobPort")
    public JobPortType getJobPort(WebServiceFeature... features) {
        return super.getPort(JobPort, JobPortType.class, features);
    }

}
